print ("-> Questão 1:")
print ("Hello World")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 2:")
Name = input("Your Name: ").capitalize()
print (f"Hello, {Name}!")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 3:")
Age = input("Your Age: ")
print (f"Your Age is {Age}.")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 4:")
Nome = str(input("Digite seu Nome: "))
Idade = int(input("Digite sua Idade: "))
print (f"Olá, {Nome}!")
print (f"A Idade Informada foi {Idade} Anos.")      
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 5:")
Nome = str(input("Digite seu Nome: "))
Idade = int(input("Digite sua Idade: "))
print (f"Olá, {Nome}! A Idade Informada foi {Idade} Anos.")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 6:")
Número_1 = int(input("Número 1: "))
Número_2 = int(input("Número 2: "))
Resultado = int(Número_1+Número_2)
print (f"Resultado: {Resultado}") 
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 7:")
Número_1 = int(input("Número 1: "))
Número_2 = int(input("Número 2: "))
Resultado = int(Número_1-Número_2)
print (f"Resultado: {Resultado}") 
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 8:")
Número_1 = int(input("Número 1: "))
Número_2 = int(input("Número 2: "))
Resultado = int(Número_1*Número_2)
print (f"Resultado: {Resultado}") 
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 9:")
Número_1 = int(input("Número 1: "))
Número_2 = int(input("Número 2: "))
Resultado = int(Número_1/Número_2)
print (f"Resultado: {Resultado}") 
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 10:")
Número_1 = int(input("Número 1: "))
Número_2 = int(input("Número 2: "))
Resultado = int(Número_1%Número_2)
print (f"Resultado: {Resultado}") 
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 11:")
Número_1 = int(input("Número 1: "))
Número_2 = int(input("Número 2: "))
Resultado = int(Número_1//Número_2)
print(f"Resultado: {Resultado}") 
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 12:")
Número = int(input("Número Escolhido: "))
Resultado = int(Número**2)
print (f"Resultado: {Resultado}") 
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 13:")
Number_1 = 10
Number_2 = 20
print (Number_1 == Number_2)
print (Number_1 != Number_2)
print (Number_1 >= Number_2)
print (Number_1 <= Number_2)
print (Number_1 > Number_2)
print (Number_1 < Number_2)
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 14:")
Email = ("jpaulo@infinityschoool.com.br")
print (type(Email))
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 15:")
Letra = ("C")
print (type(Letra))
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 16:")
Number = 10
print (type(Number))
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 17:")
Number = 1.87
print (type(Number))
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 18:")
Life = False
print (type(Life))
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 19:")
String_1 = ("Olá!")
String_2 = ("Bom Dia!")
print (f"{String_1} {String_2}")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> Questão 20:")
Number_1 = 10
Number_2 = 25
print (f"O Número {Number_1} é Menor que o Número {Number_2}")
print ("------------------------------------------------------------------------------------------------------------------------------")