print ("-> 1: Types")
print ("(str) = Significa Frase ou Número Escrito")
print ("(int) = Sgnifica Números ou Algoritmos Inteiros")
print ("(float) = Significa Números ou Algoritmos Decimais")
print ("(bool) = Significa Lógica (Permeia em True ou False")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 2: Exemplo")
Character_Name = ("Arwen Sacredshield")
Age = 28
Height = 1.75
Signed_Up = True
print (type (Character_Name))
print (type (Age))
print (type (Height))
print (type (Signed_Up))
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 3: Operações Matemáticas")
print ("+ = Significa Adição")
print ("- = Significa Subtração")
print ("* = Significa Multiplicação")
print ("/ = Significa Divisão")
print ("** = Significa Potenciação")
print ("// = Significa Divisão Inteira")
print ("% = Significa Resto da Divisão")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 4: Exemplo")
Número_1 = 8
Número_2 = 5
print (Número_1 + Número_2)
print (Número_1 - Número_2)
print (Número_1 * Número_2)
print (Número_1 / Número_2)
print (Número_1 ** Número_2)
print (Número_1 // Número_2)
print (Número_1 % Número_2)
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 5: Operações Matemáticas Comparativas")
print ("== = Verifica se Valor é Igual a Outro")
print ("!= = Verifica se Valor é Diferente de Outro")
print ("> = Verifica se Valor é Maior que Outro")
print ("< = Verifica se Valor é Menor que Outro")
print (">= = Verifica se Valor é Maior ou Igual (Obs: Basta 1 Confirmação das 2 para True)")
print ("<= = Verifica se Valor é Menor ou Igual (Obs: Basta 1 Confirmação das 2 para True)")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 6: Exemplo")
Número_1 = 10
Número_2 = 6
print (Número_1 == Número_2)
print (Número_1 != Número_2)
print (Número_1 > Número_2)
print (Número_1 < Número_2)
print (Número_1 >= Número_2)
print (Número_1 <= Número_2)
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 7: Dados Inseridos pelo Usuário")
print ("input(?)")
print ("Input = Significa Inserção de Dados pelo Usuário")
print ("O Type pode ser Demilitado no Input = str(input(?)) ou int(input(?)) ou float(input(?))")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 8: Exemplo")
Nome = str(input("Nome Completo: "))
print (Nome)
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 9: Combinação de Types na Linha")
print ("Utilizar f após Parêntenses, Escrever String + Type Escolhido entre Chaves")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 10: Exemplo")
Character_Age = int(input("Character Age: "))
print (f"Your Character Age is {Character_Age}")
print ("------------------------------------------------------------------------------------------------------------------------------")
print ("-> 11: Observações Importantes")
print ("Programas Importantes: Visual Studio Code + Git Hub")
print ("Nomes Compostos usam _ ou AaBb")
print ("# no Começo da Linha Transforma em Comentário")
print ("Comentar em Massa: Selecionar Tudo, Ctrl + ;")
print ("Desfazer = Ctrl + Z")
print ("Refazer = Ctrl + Y")
print ("Par = 0 e Ímpar = 1")
print ("Espaços Entre Chaves no Uso do f para Concatenar é Levado em Consideração ao Executar")
print ("------------------------------------------------------------------------------------------------------------------------------")